### ISSUE TITLE
Tool exploration

### ISSUE THREAD

**Issue by j-harbin** [dfo-mar-odis/ScienceSPA#24]

**Comment by j-harbin** [comment]
Proposed Change/Activity
Tool explortation

Why is this important
Ensure we're investing our time in the most appropriate application for our tasks

Action Items
Create a one page comparison of pros and cons of using different tools to create dashboard e.g. PowerBI, ShinyApp

**Comment by j-harbin** [comment]
@gomezcatalina , I think we've pretty confidentially agreed on PowerBI over shiny. Do you agree? If so, I'll close this issue.

**Comment by gomezcatalina** [comment]
I think so. It sounds like Jeff will be building on his existing PowerBI tool, instead of starting a brand new one?

**Comment by j-harbin** [comment]
I agree! I'll close this issue.
