### ISSUE TITLE
Create drawing dashboard v.1.0

### ISSUE THREAD

**Issue by j-harbin** [dfo-mar-odis/ScienceSPA#8]

**Comment by j-harbin** [comment]
Create a drawing of dashboard v.1.0 to visualize product owner's hope.

**Comment by j-harbin** [comment]
@gomezcatalina , is this something that may have already been completed by Tana and presented in the last Friday meeting? Could these images be uploaded to this issue?

**Comment by gomezcatalina** [comment]
I think this is the drawing I already added to another issue. I was remote during the meeting on Friday so I did not see her new drawings.

**Comment by j-harbin** [comment]
Tana has been completed this (see below). I'll close this issue but wanted to tag @gomezcatalina , @cstortini , and @jeff-jackson-dfo because it's a good reference figure.







![Image](https://github.com/dfo-mar-odis/ScienceSPA/assets/58750538/b4181b64-7d2f-49e1-9b04-18b86035a6b2)
